FROM golang:1.26-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o /out/migrate ./cmd/migrate


FROM alpine:3.20

WORKDIR /app

COPY --from=builder /out/migrate ./migrate
COPY sql/migrations /app/migrations

EXPOSE 443

ENTRYPOINT ["./migrate"]