services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend
    secrets:
      - db_pass

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config:/app/config
    networks:
      - backend
    secrets:
      - db_pass

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./config:/app/config
      - ./tls:/app/tls
    ports:
      - "443:443"
    networks:
      - backend
    secrets:
      - db_pass
      - tg_token
      - github_id
      - github_secret

networks:
  backend:

secrets:
  db_pass:
    file: ./secret/db_pass
  tg_token:
    file: ./secret/tg_token
  github_id:
    file: ./secret/github_id
  github_secret:
    file: ./secret/github_secret

volumes:
  pgdata:
